version: '3.8'

services:
  db:
    image: postgres:15
    container_name: diagnostics_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: diagnostics_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  backend:
    build: ./backend
    container_name: diagnostics_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=diagnostics_db
      - DB_HOST=db
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
